/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package owner;

//import UCollege.ConnectionManager;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Esha_1
 */
public class university extends javax.swing.JFrame {

    /**
     * Creates new form university
     */
    public university() {
        initComponents();
       getContentPane().setBackground(Color.GRAY);
                Date d=new Date();
       datelbl.setText(d.toString());
       datelbl1.setText(d.toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        viewcollege = new javax.swing.JPanel();
        viewcollegebtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewCollegetbl = new javax.swing.JTable();
        deletecollege = new javax.swing.JPanel();
        deletebtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        delcollname = new javax.swing.JTextField();
        sentmessages = new javax.swing.JPanel();
        sentbtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        sentMsgtbl = new javax.swing.JTable();
        compose = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        from = new javax.swing.JTextField();
        composebtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        messagetext = new javax.swing.JTextArea();
        receivemessages = new javax.swing.JPanel();
        receivedbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        receivedMsgtbl = new javax.swing.JTable();
        updatecollege = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        collname = new javax.swing.JTextField();
        colladdress = new javax.swing.JTextField();
        collphone = new javax.swing.JTextField();
        collusername = new javax.swing.JTextField();
        collpassword = new javax.swing.JTextField();
        updatebtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        searchtext = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        uploadfile = new javax.swing.JPanel();
        clickcloudbtn = new javax.swing.JButton();
        pswd = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        downloadlogtbl = new javax.swing.JTable();
        addcollege = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        caddress = new javax.swing.JTextField();
        cphone = new javax.swing.JTextField();
        cusername = new javax.swing.JTextField();
        cpassword = new javax.swing.JTextField();
        submitbtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cques = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cans = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        clgname = new javax.swing.JTextField();
        restorebtn = new javax.swing.JButton();
        datelbl1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        datelbl = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));

        viewcollege.setBackground(new java.awt.Color(51, 204, 255));
        viewcollege.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewcollegebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewcollegebtn.setText("VIEW ALL COLLEGES");
        viewcollegebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcollegebtnActionPerformed(evt);
            }
        });
        viewcollege.add(viewcollegebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        viewCollegetbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(viewCollegetbl);

        viewcollege.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 690, 90));

        jTabbedPane1.addTab("View All Colleges", viewcollege);

        deletecollege.setBackground(new java.awt.Color(204, 204, 255));
        deletecollege.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deletebtn.setBackground(new java.awt.Color(255, 153, 255));
        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(102, 51, 255));
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        deletecollege.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 161, -1, -1));

        jLabel13.setText("Enter College Name");
        deletecollege.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));
        deletecollege.add(delcollname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 110, -1));

        jTabbedPane1.addTab("Delete College", deletecollege);

        sentmessages.setBackground(new java.awt.Color(204, 204, 204));
        sentmessages.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sentbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sentbtn.setText("VIEW ALL SENT MESSAGES");
        sentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentbtnActionPerformed(evt);
            }
        });
        sentmessages.add(sentbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        sentMsgtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(sentMsgtbl);

        sentmessages.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 690, 90));

        jTabbedPane1.addTab("Sent Messages", sentmessages);

        compose.setBackground(new java.awt.Color(0, 153, 204));
        compose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Compose");
        compose.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel21.setText("To");
        compose.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel22.setText("From");
        compose.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel23.setText("Message");
        compose.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));
        compose.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 120, -1));

        from.setEditable(false);
        from.setText("admin");
        compose.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 120, -1));

        composebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        composebtn.setText("SEND");
        composebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                composebtnActionPerformed(evt);
            }
        });
        compose.add(composebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        messagetext.setColumns(20);
        messagetext.setRows(5);
        jScrollPane3.setViewportView(messagetext);

        compose.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 150, 80));

        jTabbedPane1.addTab("Compose", compose);

        receivemessages.setBackground(new java.awt.Color(204, 255, 204));
        receivemessages.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        receivedbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        receivedbtn.setText("VIEW ALL RECEIVED MESSAGES");
        receivedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivedbtnActionPerformed(evt);
            }
        });
        receivemessages.add(receivedbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        receivedMsgtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(receivedMsgtbl);

        receivemessages.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 600, 90));

        jTabbedPane1.addTab("Receive Message", receivemessages);

        updatecollege.setBackground(new java.awt.Color(255, 204, 204));
        updatecollege.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Update College Info");
        updatecollege.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel8.setText(" College Name");
        updatecollege.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel9.setText(" College Address");
        updatecollege.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel10.setText(" College Phone no");
        updatecollege.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel11.setText(" College Username");
        updatecollege.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel12.setText(" College Password");
        updatecollege.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        collname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collnameActionPerformed(evt);
            }
        });
        updatecollege.add(collname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 140, -1));
        updatecollege.add(colladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 140, -1));
        updatecollege.add(collphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 140, -1));
        updatecollege.add(collusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 140, -1));
        updatecollege.add(collpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 140, -1));

        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        updatecollege.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jLabel15.setText("Enter College ID");
        updatecollege.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));
        updatecollege.add(searchtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 150, -1));

        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchbtn.setText("SEARCH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        updatecollege.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jTabbedPane1.addTab("Update College Info", updatecollege);

        uploadfile.setBackground(new java.awt.Color(255, 255, 102));
        uploadfile.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                uploadfileComponentShown(evt);
            }
        });
        uploadfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clickcloudbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clickcloudbtn.setText("CLICK HERE FOR CLOUD CONNECTION");
        clickcloudbtn.setEnabled(false);
        clickcloudbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickcloudbtnActionPerformed(evt);
            }
        });
        uploadfile.add(clickcloudbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));
        uploadfile.add(pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 100, -1));

        jLabel18.setText("Enter Password");
        uploadfile.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 130, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Enter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        uploadfile.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jTabbedPane1.addTab("Upload File", uploadfile);

        jPanel2.setBackground(new java.awt.Color(255, 153, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("VIEW ALL DOWNLOADLOGS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        downloadlogtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(downloadlogtbl);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, 690, 91));

        jTabbedPane1.addTab("Downloadlogs", jPanel2);

        addcollege.setBackground(new java.awt.Color(243, 162, 65));
        addcollege.setForeground(new java.awt.Color(255, 255, 51));
        addcollege.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Add New College");
        addcollege.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 41, -1, -1));

        jLabel2.setText("Enter College Name");
        addcollege.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel3.setText("Enter College Address");
        addcollege.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel4.setText("Enter College Phone No");
        addcollege.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel5.setText("Enter College Username");
        addcollege.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel6.setText("Enter College Password");
        addcollege.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));
        addcollege.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 210, -1));
        addcollege.add(caddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 210, -1));
        addcollege.add(cphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 210, -1));
        addcollege.add(cusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 210, -1));
        addcollege.add(cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 210, -1));

        submitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitbtn.setText("SUBMIT");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        addcollege.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        jLabel14.setText("Secret Question");
        addcollege.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 100, 20));
        addcollege.add(cques, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 210, 30));

        jLabel16.setText("Secret Answer");
        addcollege.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));
        addcollege.add(cans, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 210, -1));

        jButton3.setText("PRINT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        addcollege.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        jTabbedPane1.addTab("Add New College", addcollege);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Enter College Name");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 130, 30));
        jPanel3.add(clgname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 130, 30));

        restorebtn.setText("RESTORE");
        restorebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restorebtnActionPerformed(evt);
            }
        });
        jPanel3.add(restorebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));
        jPanel3.add(datelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 354, 330, 20));

        jTabbedPane1.addTab("Restore College", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 700, 390));

        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 0, 0));
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));
        getContentPane().add(datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 340, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        ResultSet rs=null;
        Statement stmt=null;
        
        String name=cname.getText();
       String pswrd=cpassword.getText();
       String phno=cphone.getText();
       String username=cusername.getText();
       String cquestion=cques.getText();
       String canswer=cans.getText();
       if((cname.getText().length()==0) && (cpassword.getText().length()==0) && (cphone.getText().length()==0) && (cusername.getText().length()==0) && (caddress.getText().length()==0))
       {
           JOptionPane.showMessageDialog(this,"Please enter the fields");
       }
       
       else if(!name.matches("[a-zA-Z_]+")){       
       
            JOptionPane.showMessageDialog(this,"name Should not contain number");
       }
     else if(pswrd.length()<6)
         
              {
                 JOptionPane.showMessageDialog(this,"Password Should be minimum 6 characters");
              }
     else if(phno.length()<10)
     {
         JOptionPane.showMessageDialog(this,"Phone number Should be minimum 10 characters");
     }
      else if(phno.length()>10)
     {
         JOptionPane.showMessageDialog(this,"Phone number Should be minimum 10 characters");
     }
      else if(!phno.matches("[0-9]+")){       
       
            JOptionPane.showMessageDialog(this,"phone number Should not contain characters");
       }
     else if(!username.matches("[a-zA-Z_]+"))
       {
            JOptionPane.showMessageDialog(this,"username Should not contain number");
       }
     
        else
     {
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con=ConnectionManager.getConnection();
//            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/College","root","root");
            stmt=con.createStatement();
            rs=stmt.executeQuery("Select * from collegebackup where cname='"+cname.getText()+"'");
            if(rs.next()){
                JOptionPane.showMessageDialog(this,"College already present in collegebackup\n please restored the data");
                
            }else{
            int x=stmt.executeUpdate("insert into collegeinfo(cname,caddress,cphone,cusername,cpassword,cquestion,canswer)values('"+cname.getText()+"','"+caddress.getText()+"','"+cphone.getText()+"','"+cusername.getText()+"','"+cpassword.getText()+"','"+cques.getText()+"','"+cans.getText()+"')");
            if(x!=0)
            {
                JOptionPane.showMessageDialog(this,"College added succesfully");
            }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"This College Name Already Exist");
        }
       
     }
       
    }//GEN-LAST:event_submitbtnActionPerformed

    private void viewcollegebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcollegebtnActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        ResultSet rs=null;
        Statement stmt=null;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con=ConnectionManager.getConnection();
            //con=DriverManager.getConnection("jdbc:mysql://localhost:3306/College","root","root");
            stmt=con.createStatement();
            rs=stmt.executeQuery("select cname,caddress,cphone from collegeinfo");
            viewCollegetbl.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_viewcollegebtnActionPerformed

    private void sentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentbtnActionPerformed
        // TODO add your handling code here:
          Connection con=null;
       ResultSet rs=null;
       Statement stmt=null;
       String sql="select * from messages where sender='admin'";
       try{
           con=ConnectionManager.getConnection();
           stmt=con.createStatement();
           rs=stmt.executeQuery(sql);
           sentMsgtbl.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
       
    }//GEN-LAST:event_sentbtnActionPerformed

    private void composebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_composebtnActionPerformed
        // TODO add your handling code here:
        if(to.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Enter the receiver name");
        }else{
         Connection con=null;
       ResultSet rs=null;
       Statement stmt=null;
       String sql="insert into messages values('"+to.getText()+"','"+from.getText()+"','"+messagetext.getText()+"')";
       try{
           con=ConnectionManager.getConnection();
           stmt=con.createStatement();
           int x=stmt.executeUpdate(sql);
       
           if(x!=0)
           {
        
               JOptionPane.showMessageDialog(this, "your message has sent");
            }
          else
            {
                JOptionPane.showMessageDialog(this,"message sending failed");
            }
          }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,e);
       }
       
        }                 
    }//GEN-LAST:event_composebtnActionPerformed

    private void receivedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivedbtnActionPerformed
        // TODO add your handling code here:
          Connection con=null;
       ResultSet rs=null;
       Statement stmt=null;
       String sql="select sender,message from messages where sender!='admin'";
       try{
           con=ConnectionManager.getConnection();
           stmt=con.createStatement();
           rs=stmt.executeQuery(sql);
           receivedMsgtbl.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
        
    }//GEN-LAST:event_receivedbtnActionPerformed

    private void collnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collnameActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        if(searchtext.getText().equals("")){
            JOptionPane.showMessageDialog(this, "College ID should not blank");
        }else{
        Connection con=null;
        Statement stmt=null;
        ResultSet rs=null;
        String sql="select * from collegeinfo where collegeid='"+searchtext.getText()+"'";
        try
        {
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            if(rs.next())
            {
                collname.setText(rs.getString(1));
                colladdress.setText(rs.getString(2));
                collphone.setText(rs.getString(3));
                collusername.setText(rs.getString(4));
                collpassword.setText(rs.getString(5));
            }
            else
            {
                JOptionPane.showMessageDialog(this,"no such college exist");
            }
        }
            catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this,e);
                    }
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        Statement stmt=null;
        ResultSet rs=null;
        String cusername=collusername.getText();
       String cpassword=collpassword.getText();
       String cphone=collphone.getText();
       String name=collname.getText();
       String address=colladdress.getText();
       if((collusername.getText().length()==0) && (collpassword.getText().length()==0) && (collphone.getText().length()==0) && (collusername.getText().length()==0) && (colladdress.getText().length()==0))
       {
           JOptionPane.showMessageDialog(this,"Please enter the fields");
       }
       if(!name.matches("[a-zA-Z_]+")){       
       
            JOptionPane.showMessageDialog(this,"name Should not contain number");
       }
     else if(cphone.length()!=10)
         
              {
                 JOptionPane.showMessageDialog(this,"Phone Number Should be minimum 10 characters");
              }
     else if(cpassword.length()<6)
     {
         JOptionPane.showMessageDialog(this,"Password Should be minimum 10 characters");
     }
     else if(!cusername.matches("[a-zA-Z_]+"))
       {
            JOptionPane.showMessageDialog(this,"username Should not contain number");
       }
        else
     {
        
        
        String sql="update collegeinfo set caddress='"+colladdress.getText()+"',cphone='"+collphone.getText()+"',cusername='"+collusername.getText()+"',cpassword='"+collpassword.getText()+"' where collegeid='"+searchtext.getText()+"'";
        
        try
        {
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
           int x=stmt.executeUpdate(sql);
            if(x!=0)
            {
                
                JOptionPane.showMessageDialog(this, "Updated successfully");
                collname.setText("");
                colladdress.setText("");
                collphone.setText("");
                collusername.setText("");
                collpassword.setText("");
            }
     
        }
            catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this,e);
                    }
     }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        if(delcollname.getText().equals("")){
            JOptionPane.showMessageDialog(this, "please enter college name");
        }else{
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
        
                
        
        try
        {
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
          // int x=stmt.executeUpdate(sql);
            //if(x!=0)
               rst=stmt.executeQuery("select * from collegeinfo where cname='"+delcollname.getText()+"'");
            if(rst.next()){
               int y=stmt.executeUpdate("insert into collegebackup values('"+rst.getString(1)+"','"+rst.getString(2)+"','"+rst.getString(3)+"','"+rst.getString(4)+"','"+rst.getString(5)+"','"+rst.getString(6)+"','"+rst.getString(7)+"','"+rst.getString(8)+"')");
              String sql="delete from collegeinfo where cname='"+delcollname.getText()+"'";
               int x=stmt.executeUpdate(sql);
               if(x!=0)
               {
                   //String sql="delete from collegeinfo where cname='"+delcollname.getText()+"'";
               JOptionPane.showConfirmDialog(this, "do you want to remove");
                JOptionPane.showMessageDialog(this, "Deleted Successfully");
            }  
        
            else
            {
                JOptionPane.showMessageDialog(this, "No such college name exit");
            }
        }
        }
            catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this,e);
                    }
        
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void clickcloudbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickcloudbtnActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);
        dispose();
    }//GEN-LAST:event_clickcloudbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                Connection con=null;
        ResultSet rs=null;
        Statement stmt=null;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con=ConnectionManager.getConnection();
            //con=DriverManager.getConnection("jdbc:mysql://localhost:3306/College","root","root");
            stmt=con.createStatement();
            rs=stmt.executeQuery("select * from downloadlogs");
            downloadlogtbl.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void restorebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restorebtnActionPerformed
        // TODO add your handling code here:
        if(clgname.getText().equals("")){
            JOptionPane.showMessageDialog(this, "please enter college name");
        }else{
        Connection con=null;
       ResultSet rst=null;
       Statement stmt=null;
             try
            {
                 con=ConnectionManager.getConnection();
            stmt=con.createStatement();
        
            
               rst=stmt.executeQuery("select * from collegebackup where cname='"+clgname.getText()+"'");
            if(rst.next()){
               int y=stmt.executeUpdate("insert into collegeinfo values('"+rst.getString(1)+"','"+rst.getString(2)+"','"+rst.getString(3)+"','"+rst.getString(4)+"','"+rst.getString(5)+"','"+rst.getString(6)+"','"+rst.getString(7)+"','"+rst.getString(8)+"')");                
                JOptionPane.showConfirmDialog(this, "do you want to restore");
                JOptionPane.showMessageDialog(this, "restored Successfully");
            } 
             else
            {
                JOptionPane.showMessageDialog(this, "No such college name exit");
            }
        
           
            
        }
            catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this,"No such college exit");
                    }
   
       
         
           
          
        
        }
        
    }//GEN-LAST:event_restorebtnActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(this, "are you sure you want to logout");
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void uploadfileComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_uploadfileComponentShown
        // TODO add your handling code here:
       // passwordprompt();
        
    }//GEN-LAST:event_uploadfileComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Connection con=null;
       ResultSet rs=null;
       Statement stmt=null;
       
       String pswrd=pswd.getText();
      
        if(pswd.getText().equals(""))
       {
           JOptionPane.showMessageDialog(this,"password should not be null");
       }
    
     else if(pswrd.length()<6)
         
              {
                 JOptionPane.showMessageDialog(this,"Password Should be minimum 6 characters");
              }
        else
        {
             try
            {
           Class.forName("com.mysql.jdbc.Driver");
           con=ConnectionManager.getConnection();
           //con=DriverManager.getConnection("jdbc:mysql://localhost:3306/College","root","root");
           stmt=con.createStatement();
           rs=stmt.executeQuery("Select * from login");
           if(rs.next())
           {
       
          if(pswd.getText().equals("password"))
         {
               JOptionPane.showMessageDialog(this, "Now Your Are able to Connect with cloud");
                clickcloudbtn.setEnabled(true);
             //  new university().setVisible(true);
              // dispose();
                  
         }
          else
            {
                JOptionPane.showMessageDialog(this,"You Are NOt Able To Connect Cloud");
            }
           }
       }
       catch(Exception e)
       {
       }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        job.setPrintable(new Printable()
                {
                    public int print(Graphics pg, PageFormat pf, int pageNum)
                    {
                        if(pageNum>0)
                        {
                            return Printable.NO_SUCH_PAGE;
                        }
                    Graphics2D g2 = (Graphics2D)pg;
                    g2.translate(pf.getImageableX(), pf.getImageableY());
                    g2.scale(0.24,0.24);
                    addcollege.paint(g2);
                    return Printable.PAGE_EXISTS;
                }
               });
        boolean ok = job.printDialog();
        if(ok)
        {
            try
            {
                job.print();
            }
            catch(PrinterException ex){}
            
            }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

  /* private void passwordprompt(){
        try
        {
        javax.swing.JPasswordField pas = null;
        JOptionPane.showInputDialog(this, pas,"enter your password",JOptionPane.OK_OPTION);
          Connection con=null;
       ResultSet rs=null;
       Statement stmt=null;
      
       String pswrd=pas.getText();
       
        if(pas.getText().equals(""))
       {
           JOptionPane.showMessageDialog(this,"password should not be null");
       }
      
     else if(pswrd.length()<6)
         
              {
                 JOptionPane.showMessageDialog(this,"Password Should be minimum 6 characters");
              }
        else
        {
             try
            {
           Class.forName("com.mysql.jdbc.Driver");
           con=ConnectionManager.getConnection();
           //con=DriverManager.getConnection("jdbc:mysql://localhost:3306/College","root","root");
           stmt=con.createStatement();
           rs=stmt.executeQuery("Select * from login where username='admin' and password='"+pas.getText()+"'");
           if(rs.next())
           {
       
           }else
            {
                JOptionPane.showMessageDialog(this,"Incorrect Password");
                passwordprompt();
            }
       }
       catch(Exception e)
       {
       }
      
        }
        }
        catch(Exception e)
        {
        }/*
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(university.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(university.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(university.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(university.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new university().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addcollege;
    private javax.swing.JTextField caddress;
    private javax.swing.JTextField cans;
    private javax.swing.JTextField clgname;
    private javax.swing.JButton clickcloudbtn;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField colladdress;
    private javax.swing.JTextField collname;
    private javax.swing.JTextField collpassword;
    private javax.swing.JTextField collphone;
    private javax.swing.JTextField collusername;
    private javax.swing.JPanel compose;
    private javax.swing.JButton composebtn;
    private javax.swing.JTextField cpassword;
    private javax.swing.JTextField cphone;
    private javax.swing.JTextField cques;
    private javax.swing.JTextField cusername;
    private javax.swing.JLabel datelbl;
    private javax.swing.JLabel datelbl1;
    private javax.swing.JTextField delcollname;
    private javax.swing.JButton deletebtn;
    private javax.swing.JPanel deletecollege;
    private javax.swing.JTable downloadlogtbl;
    private javax.swing.JTextField from;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextArea messagetext;
    private javax.swing.JPasswordField pswd;
    private javax.swing.JTable receivedMsgtbl;
    private javax.swing.JButton receivedbtn;
    private javax.swing.JPanel receivemessages;
    private javax.swing.JButton restorebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchtext;
    private javax.swing.JTable sentMsgtbl;
    private javax.swing.JButton sentbtn;
    private javax.swing.JPanel sentmessages;
    private javax.swing.JButton submitbtn;
    private javax.swing.JTextField to;
    private javax.swing.JButton updatebtn;
    private javax.swing.JPanel updatecollege;
    private javax.swing.JPanel uploadfile;
    private javax.swing.JTable viewCollegetbl;
    private javax.swing.JPanel viewcollege;
    private javax.swing.JButton viewcollegebtn;
    // End of variables declaration//GEN-END:variables

}