/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HCL
 */
public class Activities extends javax.swing.JFrame {

    /**
     * Creates new form Activities
     */
    public Activities() {
        initComponents();
        Date d=new Date();
       date.setText(d.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        collegeviewreceived = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        collegereceivedMsgtbl = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        collegeviewsent = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        collegesentMsgtbl = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        collegefrom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        collegeto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        collegesendmessage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        collegemessage = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        collegeviewreceived.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        collegeviewreceived.setText("View All Received Messages");
        collegeviewreceived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeviewreceivedActionPerformed(evt);
            }
        });
        jPanel1.add(collegeviewreceived, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 11, -1, -1));

        collegereceivedMsgtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(collegereceivedMsgtbl);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 66, 646, 90));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        jTabbedPane1.addTab("Received Message", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        collegeviewsent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        collegeviewsent.setText("View All Sent Messages");
        collegeviewsent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeviewsentActionPerformed(evt);
            }
        });
        jPanel2.add(collegeviewsent, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 11, -1, -1));

        collegesentMsgtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(collegesentMsgtbl);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 66, 646, 89));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        jTabbedPane1.addTab("Sent Message", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("To");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));
        jPanel3.add(collegefrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 166, -1));

        jLabel8.setText("From");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        collegeto.setEditable(false);
        collegeto.setText("admin");
        collegeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegetoActionPerformed(evt);
            }
        });
        jPanel3.add(collegeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 166, -1));

        jLabel9.setText("Message");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        collegesendmessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        collegesendmessage.setText("Send");
        collegesendmessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegesendmessageActionPerformed(evt);
            }
        });
        jPanel3.add(collegesendmessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        collegemessage.setColumns(20);
        collegemessage.setRows(5);
        jScrollPane1.setViewportView(collegemessage);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 140, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("COMPOSE");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jTabbedPane1.addTab("Compose", jPanel3);

        date.setText("jLabel3");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("LOGOUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(jButton4)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void collegetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collegetoActionPerformed

    private void collegesendmessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegesendmessageActionPerformed
        // TODO add your handling code here:
        Connection con=null;
     Statement stmt=null;
     ResultSet rst=null;
      
String sql="insert into messages values('"+collegeto.getText()+"','"+collegefrom.getText()+"','"+collegemessage.getText()+"')";
try{
con = ConnectionManager.getConnection();
stmt = con.createStatement();
int x = stmt.executeUpdate(sql);
if(x!=0){
    JOptionPane.showMessageDialog(this, "your message has sent");
}else{
    JOptionPane.showMessageDialog(this, "message sending failed"); 
}
}catch(Exception e){
    JOptionPane.showMessageDialog(this, e);
}
    }//GEN-LAST:event_collegesendmessageActionPerformed

    private void collegeviewreceivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeviewreceivedActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;

        String sql="select sender,message from messages where sender='admin'";
        
        try{
            con = ConnectionManager.getConnection();
            stmt = con.createStatement();
             rst = stmt.executeQuery(sql);
            collegereceivedMsgtbl.setModel(DbUtils.resultSetToTableModel(rst));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_collegeviewreceivedActionPerformed

    private void collegeviewsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeviewsentActionPerformed
        // TODO add your handling code here:
         Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
         String suser=sessionclass.user;
        String sql="select receiver,message from messages where sender='"+suser+"'";
        
        try{
            con = ConnectionManager.getConnection();
            stmt = con.createStatement();
             rst = stmt.executeQuery(sql);
            collegesentMsgtbl.setModel(DbUtils.resultSetToTableModel(rst));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_collegeviewsentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new options().setVisible(true);
          dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new options().setVisible(true);
          dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new options().setVisible(true);
          dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(this, "are you sure you want to logout");
        new CollegeLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activities().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField collegefrom;
    private javax.swing.JTextArea collegemessage;
    private javax.swing.JTable collegereceivedMsgtbl;
    private javax.swing.JButton collegesendmessage;
    private javax.swing.JTable collegesentMsgtbl;
    private javax.swing.JTextField collegeto;
    private javax.swing.JButton collegeviewreceived;
    private javax.swing.JButton collegeviewsent;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
