
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the edito



import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Esha_1
 */
public class Activity extends javax.swing.JFrame {

    /**
     * Creates new form Activity
     */
    public Activity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            receivedmessage =(javax.swing.JTabbedPane)java.beans.Beans.instantiate(getClass().getClassLoader(), "Activity_receivedmessage");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jPanel1 = new javax.swing.JPanel();
        receivebtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        receivedMsgtbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        semtmessage = new javax.swing.JPanel();
        sentbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sentMsgtbl = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        compose = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        from = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        messagetext = new javax.swing.JTextArea();
        sendbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        receivebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        receivebtn.setText("VIEW ALL RECEIVED MESSAGES");
        receivebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivebtnActionPerformed(evt);
            }
        });
        jPanel1.add(receivebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 27, -1, -1));

        receivedMsgtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(receivedMsgtbl);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 683, 90));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 27, -1, -1));

        receivedmessage.addTab("Received Messages", jPanel1);

        semtmessage.setBackground(new java.awt.Color(255, 255, 153));
        semtmessage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sentbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sentbtn.setText("VIEW ALL SENT MESSAGES");
        sentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentbtnActionPerformed(evt);
            }
        });
        semtmessage.add(sentbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 28, -1, -1));

        sentMsgtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(sentMsgtbl);

        semtmessage.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 104, 683, 90));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        semtmessage.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 30, -1, -1));

        receivedmessage.addTab("Sent Messages", semtmessage);

        compose.setBackground(new java.awt.Color(255, 204, 255));
        compose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Compose");
        compose.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 11, -1, -1));

        jLabel2.setText("To");
        compose.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 64, -1, -1));

        jLabel3.setText("From");
        compose.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 133, -1, -1));

        jLabel4.setText("Message");
        compose.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 214, -1, -1));

        to.setEditable(false);
        to.setText("university");
        compose.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 58, 90, -1));

        from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromActionPerformed(evt);
            }
        });
        compose.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 130, 80, -1));

        messagetext.setColumns(20);
        messagetext.setRows(5);
        jScrollPane1.setViewportView(messagetext);

        compose.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 168, 120, 60));

        sendbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sendbtn.setText("SEND");
        sendbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbtnActionPerformed(evt);
            }
        });
        compose.add(sendbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 260, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        compose.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        receivedmessage.addTab("Compose", compose);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receivedmessage)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receivedmessage, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sendbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbtnActionPerformed
        // TODO add your handling code here:
          Connection con=null;
       ResultSet rs=null;
       Statement stmt=null;
       String sql="insert into messages values('"+to.getText()+"','"+from.getText()+"','"+messagetext.getText()+"')";
       try{
           con=(Connection) ConnectionManager.getConnection();
           stmt=con.createStatement();
           int x=stmt.executeUpdate(sql);
       
           if(x!=0)
           {
        
               JOptionPane.showMessageDialog(this, "your message has sent");
            }
          else
            {
                JOptionPane.showMessageDialog(this,"message sending failed");
            }
          }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,e);
       }
    }//GEN-LAST:event_sendbtnActionPerformed

    private void sentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentbtnActionPerformed
        // TODO add your handling code here:
               Connection con=null;
       ResultSet rs=null;
       Statement stmt=null;
       String suser=sessionclass.user;
       String sql="select receiver,message from messages where sender='"+suser+"'";
       try{
           con=(Connection) ConnectionManager.getConnection();
           stmt=con.createStatement();
           rs=stmt.executeQuery(sql);
           sentMsgtbl.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
   
    }//GEN-LAST:event_sentbtnActionPerformed

    private void receivebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivebtnActionPerformed
        // TODO add your handling code here:
            Connection con=null;
       ResultSet rs=null;
       Statement stmt=null;
       String sql="select sender,message from messages where sender='admin'";
       try{
           con=(Connection) ConnectionManager.getConnection();
           stmt=con.createStatement();
           rs=stmt.executeQuery(sql);
           receivedMsgtbl.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
        
   
    }//GEN-LAST:event_receivebtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
          new options().setVisible(true);
          dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          new options().setVisible(true);
          dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          new options().setVisible(true);
          dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel compose;
    private javax.swing.JTextField from;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea messagetext;
    private javax.swing.JButton receivebtn;
    private javax.swing.JTable receivedMsgtbl;
    private javax.swing.JTabbedPane receivedmessage;
    private javax.swing.JPanel semtmessage;
    private javax.swing.JButton sendbtn;
    private javax.swing.JTable sentMsgtbl;
    private javax.swing.JButton sentbtn;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
}
