
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Esha_1
 */
public class ques extends javax.swing.JFrame {

    /**
     * Creates new form ques
     */
    public ques() {
        initComponents();
         getContentPane().setBackground(Color.cyan);
         Date d=new Date();
       dat2lbl.setText(d.toString());
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        collname = new javax.swing.JTextField();
        chkbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cques = new javax.swing.JTextField();
        cans = new javax.swing.JTextField();
        getpassword = new javax.swing.JButton();
        dat2lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Enter UserName");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 32, 130, 40));
        getContentPane().add(collname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 90, 30));

        chkbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkbtn.setText("CHECK");
        chkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbtnActionPerformed(evt);
            }
        });
        getContentPane().add(chkbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Answer This Question");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 20));

        jLabel3.setText("Answer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        cques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cquesActionPerformed(evt);
            }
        });
        getContentPane().add(cques, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 320, -1));
        getContentPane().add(cans, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 100, -1));

        getpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getpassword.setText("Get My Password");
        getpassword.setEnabled(false);
        getpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(getpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        dat2lbl.setText("jLabel4");
        getContentPane().add(dat2lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 300, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbtnActionPerformed
        // TODO add your handling code here:
        if(collname.getText().equals("")){
            JOptionPane.showMessageDialog(this, "username cannot be blank");
        }else{
        Connection con=null;
       ResultSet rs=null;
       Statement stmt=null;
      
       String sql="select cquestion from collegeinfo where cname ='"+collname.getText()+"'";
       try{
           con=ConnectionManager.getConnection();
           stmt=con.createStatement();
           rs=stmt.executeQuery(sql);
       
           if(rs.next())
           {
        cques.setText(rs.getString(1));
          getpassword.setEnabled(true);
              
            }
          else
            {
                JOptionPane.showMessageDialog(this,"no such college");
               
            }
          }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,e);
             
       }
        
        }                                
        
    }//GEN-LAST:event_chkbtnActionPerformed

    private void cquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cquesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cquesActionPerformed

    private void getpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getpasswordActionPerformed
        // TODO add your handling code here:
        
        Connection con=null;
       ResultSet rs=null;
       Statement stmt=null;
      
       String sql="select cpassword from collegeinfo where cname ='"+collname.getText()+"' and canswer='"+cans.getText()+"' ";
       try{
           con=ConnectionManager.getConnection();
           stmt=con.createStatement();
           rs=stmt.executeQuery(sql);
       
           if(rs.next())
           {
        JOptionPane.showMessageDialog(this,"your password is"+rs.getString(1));
                        new CollegeLogin().setVisible(true);
                        dispose();

              
            }
          else
            {
                JOptionPane.showMessageDialog(this,"answer is wrong");
            }
          }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,e);
       }
        
        
        
        
    }//GEN-LAST:event_getpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                //new CollegeLogin().setVisible(true);
                

                new ques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cans;
    private javax.swing.JButton chkbtn;
    private javax.swing.JTextField collname;
    private javax.swing.JTextField cques;
    private javax.swing.JLabel dat2lbl;
    private javax.swing.JButton getpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
