/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Esha_1
 */
public class StudentData extends javax.swing.JFrame {

    /**
     * Creates new form StudentData
     */
    public StudentData() {
        initComponents();
        Date d=new Date();
       date1.setText(d.toString());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        addstudent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        saddress = new javax.swing.JTextField();
        sphoneno = new javax.swing.JTextField();
        scourse = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ssem = new javax.swing.JTextField();
        submitbtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        sregno = new javax.swing.JTextField();
        searchstudent = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        searchstudinfo = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        phonelbl = new javax.swing.JLabel();
        addresslbl = new javax.swing.JLabel();
        semlbl = new javax.swing.JLabel();
        updatestudent = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        updatename = new javax.swing.JTextField();
        updatephone = new javax.swing.JTextField();
        updateaddress = new javax.swing.JTextField();
        updatesem = new javax.swing.JTextField();
        updatebtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        updatesearch = new javax.swing.JTextField();
        updatesearchbtn = new javax.swing.JButton();
        editmarks = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        editsearch = new javax.swing.JTextField();
        editsearchbtn = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        editsub1 = new javax.swing.JTextField();
        editsub2 = new javax.swing.JTextField();
        editsub3 = new javax.swing.JTextField();
        editsub4 = new javax.swing.JTextField();
        editsub5 = new javax.swing.JTextField();
        editbtn = new javax.swing.JButton();
        searchmarks = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        searchmarksinfo = new javax.swing.JTextField();
        marksbtn = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        sub1lbl = new javax.swing.JLabel();
        sub2lbl = new javax.swing.JLabel();
        sub3lbl = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        avglbl = new javax.swing.JLabel();
        gradelbl = new javax.swing.JLabel();
        sub4lbl = new javax.swing.JLabel();
        sub5lbl = new javax.swing.JLabel();
        totallbl = new javax.swing.JLabel();
        addmarks = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sub1 = new javax.swing.JTextField();
        sub2 = new javax.swing.JTextField();
        sub3 = new javax.swing.JTextField();
        sub4 = new javax.swing.JTextField();
        sub5 = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        marksregno = new javax.swing.JTextField();
        dalbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        date1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addstudent.setBackground(new java.awt.Color(204, 204, 255));
        addstudent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Add New Student");
        addstudent.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 11, -1, -1));

        jLabel2.setText("Enter Student Name");
        addstudent.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 58, -1, -1));

        jLabel3.setText("Enter Student Address");
        addstudent.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 238, -1, 20));

        jLabel4.setText("Enter Student Phone no");
        addstudent.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 131, -1, -1));

        jLabel5.setText("Enter Student Course");
        addstudent.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 171, -1, -1));
        addstudent.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 55, 116, -1));
        addstudent.add(saddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 238, 116, -1));

        sphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sphonenoActionPerformed(evt);
            }
        });
        addstudent.add(sphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 128, 116, -1));
        addstudent.add(scourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 168, 116, -1));

        jLabel6.setText("Enter Student Sem");
        addstudent.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 211, -1, -1));

        ssem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssemActionPerformed(evt);
            }
        });
        addstudent.add(ssem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 208, 116, -1));

        submitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitbtn.setText("SUBMIT");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        addstudent.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 298, -1, -1));

        jLabel20.setText("Enter Student Register No");
        addstudent.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 98, -1, 20));
        addstudent.add(sregno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 98, 116, -1));

        jTabbedPane1.addTab("Add New Student", addstudent);

        searchstudent.setBackground(new java.awt.Color(153, 204, 255));
        searchstudent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Enter Student Register no");
        searchstudent.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 21, -1, -1));
        searchstudent.add(searchstudinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 21, 90, -1));

        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchbtn.setText("SEARCH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        searchstudent.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 20, -1, -1));

        jLabel29.setText("Student Name");
        searchstudent.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 92, -1, -1));

        jLabel31.setText("Student phone no");
        searchstudent.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 152, -1, -1));

        jLabel33.setText("Student address");
        searchstudent.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 215, -1, -1));

        jLabel35.setText("Student sem");
        searchstudent.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 276, -1, -1));
        searchstudent.add(namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 92, 75, 24));
        searchstudent.add(phonelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 152, 89, 27));
        searchstudent.add(addresslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 215, 76, 25));
        searchstudent.add(semlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 276, 76, 26));

        jTabbedPane1.addTab("Search Student", searchstudent);

        updatestudent.setBackground(new java.awt.Color(255, 153, 204));
        updatestudent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Update Student");
        updatestudent.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 63, -1, -1));

        jLabel15.setText("Student Name");
        updatestudent.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 122, 70, -1));

        jLabel16.setText("Student Phone no");
        updatestudent.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 169, 90, -1));

        jLabel17.setText("Student Address");
        updatestudent.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 205, -1, -1));

        jLabel18.setText("Student Sem");
        updatestudent.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 252, -1, -1));

        updatename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatenameActionPerformed(evt);
            }
        });
        updatestudent.add(updatename, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 116, 90, -1));
        updatestudent.add(updatephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 159, 90, -1));

        updateaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateaddressActionPerformed(evt);
            }
        });
        updatestudent.add(updateaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 199, 90, -1));
        updatestudent.add(updatesem, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 249, 90, -1));

        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        updatestudent.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 289, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Enter Student Regno");
        updatestudent.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 166, 20));
        updatestudent.add(updatesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 14, 90, -1));

        updatesearchbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatesearchbtn.setText("SEARCH");
        updatesearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatesearchbtnActionPerformed(evt);
            }
        });
        updatestudent.add(updatesearchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 10, -1, -1));

        jTabbedPane1.addTab("Update Student", updatestudent);

        editmarks.setBackground(new java.awt.Color(204, 204, 255));
        editmarks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Edit Marks");
        editmarks.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 73, -1, -1));

        jLabel22.setText("Subject 1");
        editmarks.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel23.setText("Subject 2");
        editmarks.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Enter Student Regno");
        editmarks.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 10, 142, -1));
        editmarks.add(editsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 110, -1));

        editsearchbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editsearchbtn.setText("SEARCH");
        editsearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editsearchbtnActionPerformed(evt);
            }
        });
        editmarks.add(editsearchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel25.setText("Subject 3");
        editmarks.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel26.setText("Subject 4");
        editmarks.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel27.setText("Subject 5");
        editmarks.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));
        editmarks.add(editsub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 70, -1));
        editmarks.add(editsub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 70, -1));
        editmarks.add(editsub3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 70, -1));
        editmarks.add(editsub4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 70, -1));
        editmarks.add(editsub5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 70, -1));

        editbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editbtn.setText("EDIT");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });
        editmarks.add(editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 270, -1, -1));

        jTabbedPane1.addTab("Edit Marks", editmarks);

        searchmarks.setBackground(new java.awt.Color(102, 255, 255));
        searchmarks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Enter Student Regno");
        searchmarks.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));
        searchmarks.add(searchmarksinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 30, 90, -1));

        marksbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        marksbtn.setText("SEARCH");
        marksbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marksbtnActionPerformed(evt);
            }
        });
        searchmarks.add(marksbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 30, -1, -1));

        jLabel32.setText("Subject 1");
        searchmarks.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 102, -1, -1));

        jLabel34.setText("Subject 2");
        searchmarks.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 142, -1, -1));

        jLabel36.setText("Subject 3");
        searchmarks.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 192, -1, -1));

        jLabel37.setText("Subject 4");
        searchmarks.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 236, -1, -1));

        jLabel38.setText("Subject 5");
        searchmarks.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 276, -1, -1));
        searchmarks.add(sub1lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 102, -1, -1));
        searchmarks.add(sub2lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 142, -1, -1));
        searchmarks.add(sub3lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 192, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setText("Total");
        searchmarks.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 112, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setText("Average");
        searchmarks.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 152, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel41.setText("Grade");
        searchmarks.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 192, 70, -1));
        searchmarks.add(avglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 152, 70, 30));
        searchmarks.add(gradelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 192, 130, 30));
        searchmarks.add(sub4lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 228, 60, 22));
        searchmarks.add(sub5lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 276, 78, 24));
        searchmarks.add(totallbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 113, 43, 21));

        jTabbedPane1.addTab("Search Marks", searchmarks);

        addmarks.setBackground(new java.awt.Color(255, 153, 153));
        addmarks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Add Marks");
        addmarks.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 18, 98, 25));

        jLabel8.setText("Subject 1");
        addmarks.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel9.setText("Subject 2");
        addmarks.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 128, -1, -1));

        jLabel10.setText("Subject 3");
        addmarks.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 166, -1, -1));

        jLabel11.setText("Subject 4");
        addmarks.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 201, -1, 20));

        jLabel12.setText("Subject 5");
        addmarks.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 227, -1, 33));
        addmarks.add(sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 87, 70, -1));
        addmarks.add(sub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 125, 70, -1));

        sub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub3ActionPerformed(evt);
            }
        });
        addmarks.add(sub3, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 163, 70, -1));

        sub4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub4ActionPerformed(evt);
            }
        });
        addmarks.add(sub4, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 201, 70, -1));

        sub5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub5ActionPerformed(evt);
            }
        });
        addmarks.add(sub5, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 233, 70, -1));

        addbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        addmarks.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 277, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Enter Register No");
        addmarks.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 49, -1, -1));
        addmarks.add(marksregno, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 49, 70, -1));
        addmarks.add(dalbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 280, -1));

        jTabbedPane1.addTab("Add Marks", addmarks);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        ResultSet rs=null;
        Statement stmt=null;
           String name=sname.getText();
       
       String phno=sphoneno.getText();
       String regno=sregno.getText();
       if((sname.getText().length()==0) && (sregno.getText().length()==0) && (sphoneno.getText().length()==0) && (scourse.getText().length()==0) && (saddress.getText().length()==0) && (ssem.getText().length()==0))
       {
           JOptionPane.showMessageDialog(this,"Please enter the fields");
       }
     else  if(!name.matches("[a-zA-Z_]+")){       
       
            JOptionPane.showMessageDialog(this,"name Should not contain number");
       }
     else if(phno.length()<10)
         
              {
                 JOptionPane.showMessageDialog(this,"Phone Number Should be minimum 10 characters");
              }
        else if(phno.length()>10)
     {
         JOptionPane.showMessageDialog(this,"Phone number Should be minimum 10 characters");
     }
      else if(!phno.matches("[0-9]+")){       
       
            JOptionPane.showMessageDialog(this,"phone number Should not contain characters");
       }
     else if(regno.length()<6)
     {
         JOptionPane.showMessageDialog(this,"Register Number Should be minimum 6 characters");
     }
     
        else
     {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con=ConnectionManager.getConnection();
           // con=DriverManager.getConnection("jdbc:mysql://localhost:3306/College","root","root");
            stmt=con.createStatement();
            int x=stmt.executeUpdate("insert into student(name,regno,phone,course,sem,address)values('"+sname.getText()+"','"+sregno.getText()+"','"+sphoneno.getText()+"','"+scourse.getText()+"','"+ssem.getText()+"','"+saddress.getText()+"')");
            if(x!=0)
            {
                JOptionPane.showMessageDialog(this,"Student added succesfully");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
     }    
    }//GEN-LAST:event_submitbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        ResultSet rs=null;
        Statement stmt=null;
             String m1=sub1.getText();
       String m2=sub2.getText();
       String m3=sub3.getText();
       String m4=sub4.getText();
       String m5=sub5.getText();
       
       if((sub1.getText().length()==0) && (sub2.getText().length()==0) && (sub3.getText().length()==0) && (sub4.getText().length()==0) && (sub5.getText().length()==0))
       {
           JOptionPane.showMessageDialog(this,"Please enter the fields");
       }
     else  if(!m1.matches("[0-9]+"))
        {       
       
            JOptionPane.showMessageDialog(this,"Should Not Contain Alphabets");
       }
     else if(m1.length()<2)
         
              {
                 JOptionPane.showMessageDialog(this,"Subject1 Should be minimum 2 characters");
              }
     else  if(!m2.matches("[0-9]+"))
        {       
       
            JOptionPane.showMessageDialog(this,"Should Not Contain Alphabets");
       }
     else if(m2.length()<2)
         
              {
                 JOptionPane.showMessageDialog(this,"Subject2 Should be minimum 2 characters");
              }
     else  if(!m3.matches("[0-9]+"))
        {       
       
            JOptionPane.showMessageDialog(this,"Should Not Contain Alphabets");
       }
     else if(m3.length()<2)
         
              {
                 JOptionPane.showMessageDialog(this,"Subject3 Should be minimum 2 characters");
              }
     else  if(!m4.matches("[0-9]+"))
        {       
       
            JOptionPane.showMessageDialog(this,"Should Not Contain Alphabets");
       }
     else if(m4.length()<2)
         
              {
                 JOptionPane.showMessageDialog(this,"Subject4 Should be minimum 2 characters");
              }
     else  if(!m5.matches("[0-9]+"))
        {       
       
            JOptionPane.showMessageDialog(this,"Should Not Contain Alphabets");
       }
     else if(m5.length()<2)
         
              {
                 JOptionPane.showMessageDialog(this,"Subject5 Should be minimum 2 characters");
              }
     else
     {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con=ConnectionManager.getConnection();
          //  con=DriverManager.getConnection("jdbc:mysql://localhost:3306/College","root","root");
            stmt=con.createStatement();
            int x=stmt.executeUpdate("insert into marks(regno,sub1,sub2,sub3,sub4,sub5)values('"+marksregno.getText()+"','"+sub1.getText()+"','"+sub2.getText()+"','"+sub3.getText()+"','"+sub4.getText()+"','"+sub5.getText()+"')");
            if(x!=0)
            {
                JOptionPane.showMessageDialog(this,"Marks added succesfully");
            }
         
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
         
     }
    }//GEN-LAST:event_addbtnActionPerformed

    private void updatenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatenameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_updatenameActionPerformed

    private void updatesearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatesearchbtnActionPerformed
        // TODO add your handling code here:
         if(updatesearch.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Register Number should not be blank");
        }else{
            Connection con=null;
        Statement stmt=null;
        ResultSet rs=null;
        String sql="select name,phone,address,sem from student where regno='"+updatesearch.getText()+"'";
        try
        {
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            if(rs.next())
            {
                updatename.setText(rs.getString(1));
                updatephone.setText(rs.getString(2));
                updateaddress.setText(rs.getString(3));
                updatesem.setText(rs.getString(4));
              
            }
            else
            {
                JOptionPane.showMessageDialog(this,"no such student exist");
            }
        }
            catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this,e);
                    }
         }
    }//GEN-LAST:event_updatesearchbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
         Connection con=null;
        Statement stmt=null;
        ResultSet rs=null;
             String name=updatename.getText();
       
       String phno=updatephone.getText();
       
       if((updatename.getText().length()==0) && (updatephone.getText().length()==0) && (updateaddress.getText().length()==0) && (updatesem.getText().length()==0))
       {
           JOptionPane.showMessageDialog(this,"Please enter the fields");
       }
     else  if(!name.matches("[a-zA-Z_]+")){       
       
            JOptionPane.showMessageDialog(this,"name Should not contain number");
       }
     else if(phno.length()<10)
         
              {
                 JOptionPane.showMessageDialog(this,"Phone Number Should be minimum 10 characters");
              }
     else if(phno.length()>10)
     {
         JOptionPane.showMessageDialog(this,"Phone number Should be minimum 10 characters");
     }
      else if(!phno.matches("[0-9]+")){       
       
            JOptionPane.showMessageDialog(this,"phone number Should not contain characters");
       }
     else
     {
        String sql="update student set name='"+updatename.getText()+"',phone='"+updatephone.getText()+"',address='"+updateaddress.getText()+"',sem='"+updatesem.getText()+"' where regno='"+updatesearch.getText()+"'";
        
        try
        {
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
           int x=stmt.executeUpdate(sql);
            if(x!=0)
            {
                
                JOptionPane.showMessageDialog(this, "Updated successfully");
                updatename.setText("");
                updatephone.setText("");
                updateaddress.setText("");
                updatesem.setText("");
             
            }
     
        }
            catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this,e);
                    }
     }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void updateaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateaddressActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
          Connection con=null;
        Statement stmt=null;
        ResultSet rs=null;
          
       
       
       String sub1=editsub1.getText();
       String sub2=editsub2.getText();
       String sub3=editsub3.getText();
       String sub4=editsub4.getText();
       String sub5=editsub5.getText();
       
       if((editsub1.getText().length()==0) && (editsub2.getText().length()==0) && (editsub3.getText().length()==0) && (editsub4.getText().length()==0) && (editsub5.getText().length()==0))
       {
           JOptionPane.showMessageDialog(this,"Please enter the fields");
       }
     else  if(!sub1.matches("[0-9]+"))
        {       
       
            JOptionPane.showMessageDialog(this,"Should Not Contain Alphabets");
       }
     else if(sub1.length()<2)
         
              {
                 JOptionPane.showMessageDialog(this,"Subject1 Should be minimum 2 characters");
              }
     else  if(!sub2.matches("[0-9]+"))
        {       
       
            JOptionPane.showMessageDialog(this,"Should Not Contain Alphabets");
       }
     else if(sub2.length()<2)
         
              {
                 JOptionPane.showMessageDialog(this,"Subject2 Should be minimum 2 characters");
              }
     else  if(!sub3.matches("[0-9]+"))
        {       
       
            JOptionPane.showMessageDialog(this,"Should Not Contain Alphabets");
       }
     else if(sub3.length()<2)
         
              {
                 JOptionPane.showMessageDialog(this,"Subject3 Should be minimum 2 characters");
              }
     else  if(!sub4.matches("[0-9]+"))
        {       
       
            JOptionPane.showMessageDialog(this,"Should Not Contain Alphabets");
       }
     else if(sub4.length()<2)
         
              {
                 JOptionPane.showMessageDialog(this,"Subject4 Should be minimum 2 characters");
              }
     else  if(!sub5.matches("[0-9]+"))
        {       
       
            JOptionPane.showMessageDialog(this,"Should Not Contain Alphabets");
       }
     else if(sub5.length()<2)
         
              {
                 JOptionPane.showMessageDialog(this,"Subject5 Should be minimum 2 characters");
              }
     else
     {
        int s1=Integer.parseInt(editsub1.getText());
         int s2=Integer.parseInt(editsub2.getText());
         int s3=Integer.parseInt(editsub3.getText());
         int s4=Integer.parseInt(editsub4.getText());
         int s5=Integer.parseInt(editsub5.getText());
        
        String sql="update marks set sub1="+s1+",sub2="+s2+",sub3="+s3+",sub4="+s4+",sub5="+s5+" where regno='"+editsearch.getText()+"'";
        
        try
        {
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
           int x=stmt.executeUpdate(sql);
            if(x!=0)
            {
                
                JOptionPane.showMessageDialog(this, "Updated successfully");
                editsub1.setText("");
                editsub2.setText("");
                editsub3.setText("");
                editsub4.setText("");
                editsub5.setText("");
             
            }
     
        }
            catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this,e);
                    }
     }
    }//GEN-LAST:event_editbtnActionPerformed

    private void editsearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editsearchbtnActionPerformed
        // TODO add your handling code here:
        if(editsearch.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Register Number Should not be blank");
        }else{
             Connection con=null;
        Statement stmt=null;
        ResultSet rs=null;
        String sql="select sub1,sub2,sub3,sub4,sub5 from marks where regno='"+editsearch.getText()+"'";
        try
        {
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            if(rs.next())
            {
                editsub1.setText(rs.getString(1));
                editsub2.setText(rs.getString(2));
                editsub3.setText(rs.getString(3));
                editsub4.setText(rs.getString(4));
                editsub5.setText(rs.getString(5));
              
            }
            else
            {
                JOptionPane.showMessageDialog(this,"no such student exist");
            }
        }
            catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this,e);
                    }
    }//GEN-LAST:event_editsearchbtnActionPerformed
   }
    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
         if(searchstudinfo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Register Number Should not be blank");
        }else{
                Connection con=null;
        Statement stmt=null;
        ResultSet rs=null;
        String sql="select name,phone,address,sem from student where regno='"+searchstudinfo.getText()+"'";
        try
        {
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            if(rs.next())
            {
                namelbl.setText(rs.getString(1));
                phonelbl.setText(rs.getString(2));
                addresslbl.setText(rs.getString(3));
                semlbl.setText(rs.getString(4));
              
            }
            else
            {
                JOptionPane.showMessageDialog(this,"no such student exist");
            }
        }
            catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this,e);
                    }
         }
        
    }//GEN-LAST:event_searchbtnActionPerformed

    private void marksbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marksbtnActionPerformed
        // TODO add your handling code here:
        if(searchmarksinfo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Register Number Should not be blank");
        }else{
                    Connection con=null;
        Statement stmt=null;
        ResultSet rs=null;
        String sql="select sub1,sub2,sub3,sub4,sub5 from marks where regno='"+searchmarksinfo.getText()+"'";
        try
        {
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            if(rs.next())
            {
                sub1lbl.setText(rs.getString(1));
                int sub1=rs.getInt(1);
                sub2lbl.setText(rs.getString(2));
                int sub2=rs.getInt(2);
                sub3lbl.setText(rs.getString(3));
                int sub3=rs.getInt(3);
                sub4lbl.setText(rs.getString(4));
                int sub4=rs.getInt(4);
                sub5lbl.setText(rs.getString(5));
                int sub5=rs.getInt(5);
                int total;
                String grade=null;
                float avg;
               total=sub1+sub2+sub3+sub4+sub5;
              totallbl.setText(Integer.toString(total));
              avg=total/5;
              avglbl.setText(Float.toString(avg));
              if(sub1<40||sub2<40||sub3<40||sub4<40||sub5<40)
                  grade="FAIL";
              else
              {
                  if(avg>=70&& avg<100)
                      grade="DISTINCTION";
                  else if(avg>=60 && avg<70)
                      grade="FIRST CLASS";
                  else if(avg>=50 && avg<60)
                      grade="SECOND CLASS";
                  else if(avg>=40 && avg<50 )
                      grade="PASS";
                gradelbl.setText(grade);  
                  
              }
                
            }
            else
            {
                JOptionPane.showMessageDialog(this,"no such student exist");
            }
        }
            catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this,e);
                    }
        }
    }//GEN-LAST:event_marksbtnActionPerformed

    private void sphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sphonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sphonenoActionPerformed

    private void ssemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssemActionPerformed

    private void sub5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub5ActionPerformed

    private void sub4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub4ActionPerformed

    private void sub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showConfirmDialog(this, "are you sure you want to logout");
        new CollegeLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new options().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JPanel addmarks;
    private javax.swing.JLabel addresslbl;
    private javax.swing.JPanel addstudent;
    private javax.swing.JLabel avglbl;
    private javax.swing.JLabel dalbl;
    private javax.swing.JLabel date1;
    private javax.swing.JButton editbtn;
    private javax.swing.JPanel editmarks;
    private javax.swing.JTextField editsearch;
    private javax.swing.JButton editsearchbtn;
    private javax.swing.JTextField editsub1;
    private javax.swing.JTextField editsub2;
    private javax.swing.JTextField editsub3;
    private javax.swing.JTextField editsub4;
    private javax.swing.JTextField editsub5;
    private javax.swing.JLabel gradelbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton marksbtn;
    private javax.swing.JTextField marksregno;
    private javax.swing.JLabel namelbl;
    private javax.swing.JLabel phonelbl;
    private javax.swing.JTextField saddress;
    private javax.swing.JTextField scourse;
    private javax.swing.JButton searchbtn;
    private javax.swing.JPanel searchmarks;
    private javax.swing.JTextField searchmarksinfo;
    private javax.swing.JPanel searchstudent;
    private javax.swing.JTextField searchstudinfo;
    private javax.swing.JLabel semlbl;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField sphoneno;
    private javax.swing.JTextField sregno;
    private javax.swing.JTextField ssem;
    private javax.swing.JTextField sub1;
    private javax.swing.JLabel sub1lbl;
    private javax.swing.JTextField sub2;
    private javax.swing.JLabel sub2lbl;
    private javax.swing.JTextField sub3;
    private javax.swing.JLabel sub3lbl;
    private javax.swing.JTextField sub4;
    private javax.swing.JLabel sub4lbl;
    private javax.swing.JTextField sub5;
    private javax.swing.JLabel sub5lbl;
    private javax.swing.JButton submitbtn;
    private javax.swing.JLabel totallbl;
    private javax.swing.JTextField updateaddress;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField updatename;
    private javax.swing.JTextField updatephone;
    private javax.swing.JTextField updatesearch;
    private javax.swing.JButton updatesearchbtn;
    private javax.swing.JTextField updatesem;
    private javax.swing.JPanel updatestudent;
    // End of variables declaration//GEN-END:variables
}
